### Figuring out what's happening in example 3.11 (computation)

In [1]:
import numpy as np
import sympy as sp

First I check if U is linearly independent. After rref I see it has two pivots in its columns so this is linearly independent. 

In [2]:
B = np.array([[1, 0],
              [1, 1],
              [1, 2]])

In [3]:
x = np.array([[6],
              [0],
              [0]])

We use the equation from the text to find the matrices that help us find lambda.

In [4]:
B_T_B = np.matmul(np.transpose(B), B)
B_T_x = np.matmul(np.transpose(B), x)


B_T_B

array([[3, 3],
       [3, 5]])

In [5]:
B_T_B_inv = np.linalg.inv(B_T_B)



lam = np.matmul(B_T_B_inv, B_T_x)
mu = np.matmul(B, lam)
mu

array([[ 5.],
       [ 2.],
       [-1.]])

In [6]:
U = sp.Matrix([[0, 1, -3, -1],
              [-1, -3, 4, -3],
              [2, 1, 1, 5],
              [0, -1, 2, 0],
              [2, 2, 1, 7]])

print(U.rref())

(Matrix([
[1, 0, 0, 1],
[0, 1, 0, 2],
[0, 0, 1, 1],
[0, 0, 0, 0],
[0, 0, 0, 0]]), (0, 1, 2))


In [7]:
U = sp.Matrix([[0, 1, -3],
              [-1, -3, 4],
              [2, 1, 1],
              [0, -1, 2],
              [2, 2, 1]])

print(U.rref())

(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1, 2))


In [8]:
U = np.array([[0, 1, -3],
              [-1, -3, 4],
              [2, 1, 1],
              [0, -1, 2],
              [2, 2, 1]])

In [9]:
x = np.array([[-1],
             [-9],
             [-1],
             [4],
             [1]])

In [10]:
U_T_U = np.matmul(np.transpose(U), U)
U_T_x = np.matmul(np.transpose(U), x)

U_T_U

array([[  9,   9,   0],
       [  9,  16, -14],
       [  0, -14,  31]])

In [11]:
# Correct

U_T_U_inv = np.linalg.inv(U_T_U)

lamb = np.matmul(U_T_U_inv, U_T_x)
lamb

array([[-3.],
       [ 4.],
       [ 1.]])

In [12]:
# Correct

mu_x = np.matmul(U, lamb)
mu_x

array([[ 1.],
       [-5.],
       [-1.],
       [-2.],
       [ 3.]])

In [44]:
# Calculate the projection matrix

p = np.matmul(U, U_T_U_inv)
P = np.matmul(p, np.transpose(U))
P

array([[ 4.76190476e-01, -2.85714286e-01,  1.90476190e-01,
        -1.42857143e-01, -3.33333333e-01],
       [-2.85714286e-01,  6.82539683e-01,  6.34920635e-02,
         2.85714286e-01, -2.22222222e-01],
       [ 1.90476190e-01,  6.34920635e-02,  9.20634921e-01,
         1.42857143e-01,  1.11111111e-01],
       [-1.42857143e-01,  2.85714286e-01,  1.42857143e-01,
         1.42857143e-01,  1.11022302e-16],
       [-3.33333333e-01, -2.22222222e-01,  1.11111111e-01,
         4.44089210e-16,  7.77777778e-01]])

In [36]:
# Calculate the projection distance -- I think this means taking mu_x sum of squares
# Correct (My original thought: distance between vector and the subspaces -- so we want the projection error)


import math

distance = x - mu_x
# maybe this could be cleaned up with a lambda function or just move the math.sqrt() above
calc_distance = sum([[i][0] * [i][0] for i in distance])
sqrt_distance = math.sqrt(calc_distance)
sqrt_distance

7.745966692414834

In [39]:
distance.shape

(5, 1)

In [40]:
mu_x.shape

(5, 1)

In [43]:
# My confirmation: the projection is orthogonal to the error? 

test = np.dot(np.transpose(mu_x), distance)
test

array([[3.8191672e-14]])